### ISSUE TITLE
support 'synchronous' code with a fake loop

### ISSUE THREAD

**Issue by graingert** [crossbario/txaio#113]
add support for a mode where every Future completes synchronously.

This way someone could write an adapter that can use one of twisted.web, requests or aiohttp and still get back a future.

Client library code would use this adapter as if it were twisted.web, except if you used requests the library could provide results synchronously by querying a special property on the txaio Future.

**Comment by meejah** [comment]
The right answer for this under Twisted is "use Crochet" (https://pypi.python.org/pypi/crochet). I don't know if there's a similar thing for asyncio.

Also, txaio isn't really for "client" applications -- it's for libraries to reduce the amount of code required to present a "twisted" **or** an "asyncio" API to users. However, users of this library still have to choose one or the other. So, if they chose "Twisted" but wanted synchronous code they'd just use Crochet.
