### ISSUE TITLE
Using libraries that use asyncio and twisted

### ISSUE THREAD

**Issue by illera88** [crossbario/txaio#123]
Hi,

This code produces errors:
```
from bitex.api.WSS.bitstamp import BitstampWSS
from binance.websockets import BinanceSocketManager
```
Error:
```
Traceback (most recent call last):
  File "C:\Users\user\Documents\code\main.py", line 3, in <module>
    from binance.websockets import BinanceSocketManager
  File "C:\Python36_64\lib\site-packages\binance\websockets.py", line 7, in <module>
    from autobahn.twisted.websocket import WebSocketClientFactory, \
  File "C:\Python36_64\lib\site-packages\autobahn\twisted\__init__.py", line 41, in <module>
    from autobahn.twisted.choosereactor import install_reactor
  File "C:\Python36_64\lib\site-packages\autobahn\twisted\choosereactor.py", line 32, in <module>
    txaio.use_twisted()
  File "C:\Python36_64\lib\site-packages\txaio\__init__.py", line 108, in use_twisted
    raise RuntimeError("Explicitly using '{}' already".format(_explicit_framework))
RuntimeError: Explicitly using 'asyncio' already
```

They are external libraries that I use and not something that I coded. Have you thought about this use case?

Cheers

**Comment by meejah** [comment]
txaio is for programming a library that uses asyncio *or* twisted. It doesn't have provisions for using both at once in the same process.

The most-likely way forward would be to do one of two things

 - create a Twisted reactor implementation that "runs on top" of the asyncio reactor
 - create an asyncio event-loop implementation that "runs on top" of Twisted

If one of those two things existed, then it might be feasible to make txaio support both twisted and asyncio within the same process -- but you'd still need to take care to have the correct Deferreds/Futures be dealt with on the correct event-loop.
