### ISSUE TITLE
Advice on using `pytest-asyncio` with `txaio`

### ISSUE THREAD

**Issue by andronikosnedos-temboo** [crossbario/txaio#174]
I have the following simple test which attempts to execute a callback using `txaio`  and `pytest-asyncio`
```
import txaio
import pytest
txaio.use_asyncio()  # noqa
txaio.start_logging(level='debug')
log = txaio.make_logger()


def cb():
    log.info('callback called')


@pytest.mark.asyncio
async def test_example(event_loop):
    txa = txaio.with_config(loop=event_loop)
    f = txa.create_future()
    txa.add_callbacks(f, cb, None)
```

The callback is not being called even when I add a `return f` at the end of the test. I wonder if I'm missing something or `txaio` and `pytest-asyncio` are not compatible.

**Comment by meejah** [comment]
Does `await f` work?

Anyway, the real point of txaio is for people to develop "cross-framework" libraries .. if you intend to use just asyncio, this probably isn't going to be a good tool at all. (You can use Autobahn with asyncio "as normal" for example).

(Also, this is for tracking bugs .. better to use the forums for questions etc: https://forum.crossbar.io/)

**Comment by meejah** [comment]
(@oberstet for some reason I can't close this ...)

**Comment by andronikosnedos-temboo** [comment]
Many thanks @meejah , adding `await f` doesn't help unfortunately. I'm well aware this isn't really a bug but more of a feature request or a request for advice, so thanks for pointing me to the forum. I can close the issue.
