### ISSUE TITLE
Release v21.11.1

### ISSUE THREAD

**Issue by oberstet** [crossbario/txaio#177]
bump version and push new release ..

**Comment by om26er** [comment]
Is the release process documented somewhere ? That will enable us to help with releases in future as well

**Comment by oberstet** [comment]
no, it's not, and yes, that would be useful to have! fwiw, here is the super quick recipe:

1. bump version in [version.py](https://github.com/crossbario/txaio/blob/master/txaio/_version.py)
2. update changelog https://github.com/crossbario/txaio/blob/master/docs/releases.rst
3. tag release 
4. "make publish" to upload to https://pypi.org/project/txaio/
