### ISSUE TITLE
Polish docs

### ISSUE THREAD

**Issue by oberstet** [crossbario/txaio#28]
I've setup a GH hook that fires off RTD : http://txaio.readthedocs.org/en/latest/

We should go over the docs and add missing information, improve style and in particular cover what exactly is considered public, long-term stable API and what not.

**Comment by oberstet** [comment]
I did this https://github.com/tavendo/txaio/commit/420df87fa9f19cbccdbab4510ae01bd817ee8ef5 .. as it broke the rendering on the PyPI package page. However, this seems wrong .. as now the pages are missing at http://txaio.readthedocs.org/en/latest/

**Comment by oberstet** [comment]
I have added Sphinx spellchecking as well: `make spelling`. This should also be integrated into Travis: automatically spellcheck and build the docs. And also trigger RTD.

**Comment by oberstet** [comment]
I've fixed the thing I mentioned above rgd missing pages: there now is a full TOC sidebar.

**Comment by meejah** [comment]
It's been a while since I set one up, but my recollection is that ReadTheDocs integrates with github, including IIRC triggering builds from each build -- so I think it's just a matter of setting it up once.

**Comment by oberstet** [comment]
There needs to be 2 things configured: GH hook _and_ RTD settings must match. The repo link in the RTD settings was still pointing to the old location, and auto-building docs didn't work. I changed that now, and the docs have been automatically created for 2.1.0. So this seems to work now. Closing.
