### ISSUE TITLE
is_future helper?

### ISSUE THREAD

**Issue by hynek** [crossbario/txaio#31]
Hi,

I’m trying to write decorators that can handle coroutines and would like to write something like this generally:

```python
self.__enter__()
rv = f(*a, **kw)
if asyncio.iscoroutine(rv):
    rv = asyncio.ensure_future(rv)
    rv.add_done_callback(lambda _: self.__exit__(None, None, None))
else:
    self.__exit__(None, None, None)
return rv
```

(i.e. `iscoroutine(rv) or isinstance(rv, Deferred)`)
Briefly scrolling through txaio’s API docs didn’t uncover anything that could help me but maybe I’ve overseen something?  In any case I’d prefer to not implement it myself (also because of async/ensure_future diasphora etc). :)

P.S. See https://github.com/prometheus/client_python/issues/48 for context.

**Comment by meejah** [comment]
You could replace the ``rv = f(*a, **kw)`` with ``txaio.as_future(f, *a, **kw)``?

Something like:

```
self.__enter__()
rv = txaio.as_future(f, *a, **kw)
txaio.add_callbacks(rv, lambda _: self.__exit__(None, None, None), None)
```

**Comment by hynek** [comment]
Hm that seems excessive to wrap every result.

**Comment by oberstet** [comment]
@hynek fwiw, Autobahn uses `txaio.as_future` eg when calling a procedure a user has registered for remoting for uniform handling everywhere. This is doing fine (no performance issue).

That being said, a `txaio.is_future` seems a logical addition to txaio.

**Comment by meejah** [comment]
@hynek, @oberstet how does #40 look?

**Comment by oberstet** [comment]
released in https://pypi.python.org/pypi/txaio/2.1.0
