### ISSUE TITLE
Usages of asyncio objects (Future, Task, etc), must be provided with the loop kwarg

### ISSUE THREAD

**Issue by ajcormier** [crossbario/txaio#35]
txio takes an event loop for configuration txaio.config.loop.  Unfortunately, this is only used in the aio.call_later() function.  It should also be used in all asyncio calls (Future, Task, gather, etc).

**Comment by meejah** [comment]
#39 should fix this

**Comment by oberstet** [comment]
fixed in https://pypi.python.org/pypi/txaio/2.1.0
