### ISSUE TITLE
Importing txaio messes up logging when using trollius 

### ISSUE THREAD

**Issue by WGH-** [crossbario/txaio#45]
It starts spitting messages like 
`<LogRecord: trollius, 10, .../lib/python2.7/site-packages/trollius/selector_events.py, 72, "Using selector: %s">`

Why do you call `logging.getLogger("trollius").addHandler(PrintHandler())` without asking the user, anyway? Not to mention that your `PrintHandler` is completely broken.

**Comment by meejah** [comment]
@hawkowl this originally came from ``autobahn/_logging.py`` in Autobahn, and I'm not sure why it was there; can you comment? (Commit bf324d7a5155606ccaada639c12c9e8808d27866)

**Comment by hawkowl** [comment]
It's from https://github.com/crossbario/autobahn-python/pull/452 -- the logger was added because of https://bitbucket.org/enovance/trollius/issues/19/no-handlers-could-be-found-for-logger causing things to fail. Maybe it's not needed now? Maybe it was never a bug? Who knows :)

**Comment by meejah** [comment]
Hmm, okay thanks. I'll play with it a bit -- maybe what I should have done was move that to ``start_logging()`` so that it doesn't mess up logging as this bug originally describes
