### ISSUE TITLE
Logging changes in 55ca3e40ab create problems with older code, e.g. autobahn-python

### ISSUE THREAD

**Issue by mk-fg** [crossbario/txaio#60]
Crux of the issue seem to be that e.g. autobahn-python does things like these:

    self.log.debug("received HTTP headers in opening handshake : %s" % str(self.http_headers))

And new logging api (introduced in 55ca3e40ab, according to git-blame) does not support that, as it then calls `str.format()` on the passed string, which should never be called on essentially random string like one produced by the line above.

Link to that line in current autobahn-python: https://github.com/crossbario/autobahn-python/blob/c6ca54d794/autobahn/websocket/protocol.py#L2327

Submitted issue here, as fixing logging calls in autobahn should leave-out anyone with older autobahn and newer txaio, so thought that maybe it's possible to have fix here, making old logging calls compatible with new api instead?

A bit more details follow.

------

So, when using WAMP in autobahn-python with Python-3.5/asyncio, I'm seeing this:

```
2016-04-04 20:39:12 :: asyncio ERROR: Exception in callback WebSocketAdapterProtocol._consume.<locals>.process(<Future finished result=None>) at /home/fraggod/.py3/autobahn/asyncio/websocket.py:105
handle: <Handle WebSocketAdapterProtocol._consume.<locals>.process(<Future finished result=None>) at /home/fraggod/.py3/autobahn/asyncio/websocket.py:105>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/fraggod/.py3/autobahn/asyncio/websocket.py", line 109, in process
    self._dataReceived(data)
  File "/home/fraggod/.py3/autobahn/websocket/protocol.py", line 1176, in _dataReceived
    self.consumeData()
  File "/home/fraggod/.py3/autobahn/websocket/protocol.py", line 1205, in consumeData
    self.processHandshake()
  File "/home/fraggod/.py3/autobahn/websocket/protocol.py", line 3484, in processHandshake
    self.log.debug("received HTTP headers in opening handshake : %s" % str(self.http_headers))
  File "/home/fraggod/.py3/txaio/aio.py", line 109, in _log
    msg = log_format.format(**kwargs)
KeyError: "'sec-websocket-protocol'"
2016-04-04T20:39:12 Exception in callback WebSocketAdapterProtocol._consume.<locals>.process(<Future finished result=None>) at /home/fraggod/.py3/autobahn/asyncio/websocket.py:105
handle: <Handle WebSocketAdapterProtocol._consume.<locals>.process(<Future finished result=None>) at /home/fraggod/.py3/autobahn/asyncio/websocket.py:105>
```

Looking into txaio.aio, issue seem to be that `msg = log_format.format(**kwargs)` is with "log_format" already having templated-in data - in this case headers dict - and hence looks like this:

    received HTTP headers in opening handshake : {'sec-websocket-protocol': 'wamp.2.json.batched', ...

And then running pretty much any `str.format()` on that would inevitably produce error above, due to `{}` things in there.

**Comment by meejah** [comment]
Lines like ``self.log.debug("received HTTP headers in opening handshake : %s" % str(self.http_headers))`` should be re-written as e.g. ``self.log.debug("received HTTP headers: {headers}", headers=self.http_headers)``. So, this is really an autobahn bug.

I'm not sure if there's really any way to "fix" this in txaio -- only thing I could think of is to catch formatting exceptions and then just log the format-string as-is, but that will then hide "real" formatting errors.

**Comment by mk-fg** [comment]
Guess it makes sense for it to be backwards-incompatible change, if there's no way to fix it, pity.
I was thinking that maybe new logging api can be requested by new apps explicitly, or something, and otherwise handle messages in "ye olde way", same as with new-format stdlib logging wrappers.

Thanks for addressing this on such a short notice, should I close it myself?

**Comment by meejah** [comment]
I'm open to suggestions to fix it nicely, but txaio's logging was always supposed to be "structured" (twisted new-logger style) logging. Also, I'm not aware of anything besides Autobahn using txaio anyway ;)

I'm closing this, as I opened an Autobahn bug to address any remaining "not-structured" logging in there.

**Comment by oberstet** [comment]
Yeah, this is a AutobahnPython bug .. "use new logging"
